import streamlit as st
from .calculator import PotCalculator


def run_calculation(maxNsd: float, Vxd: float) -> None:
    """Execute the POT UNI calculation and display results via Streamlit."""
    results = PotCalculator(maxNsd, Vxd).calculate()

    st.markdown('### Dimensões gerais')
    st.write('A altura total do aparelho é {} mm'.format(results["T_total"]))
    st.write('O peso total do aparelho é {} kg'.format(results["peso_total"]))
    st.write('')
    st.image('Imagem3.png')

    st.markdown('### 1 - Elastômero')
    st.write('O Dp = {} mm'.format(results['D']))
    st.write('A espessura é hr = {} mm'.format(results['tmin']))
    st.write('O peso do elastômero é {} kg'.format(results['peso_elastomero']))
    st.write('')

    st.image('Imagem5.png')
    st.markdown('### 2 - Pote')
    st.write('O diâmetro interno Dp = {} mm'.format(results['D']))
    st.write('O diâmetro externo no pote é Dpot = {} mm'.format(2 * results['B'] + results['D']))
    st.write('A espessura do anel do pote é tw = {} mm'.format(results['B']))
    st.write('A profundidade do Dp é hp1 = {} mm'.format(results['H']))
    st.write('O diâmetro do fundo do pote é Wpot = {} mm'.format(results['D'] + results['B'] + results['B'] + results['solda'] + results['solda'] + 6))
    st.write('A espessura do fundo do pote é tb = {} mm'.format(results['T']))
    st.write('O cordão de solda é w = {} mm'.format(results['solda']))
    st.write('O peso do pote é {} kg'.format(results['peso_pote']))
    st.write('')

    st.markdown('### 3 - Pistão')
    st.write('O diâmetro de contato é Dp = {} mm'.format(results['D']))
    st.write('A altura do diâmetro de contato é hw = {} mm'.format(results['b']))
    st.write('O diâmetro externo do pistão é Dmp = {} mm'.format(results['Dpiston']))
    st.write('A altura total do pistão é hp4 = {} mm'.format(results['hpistao']))
    st.write('O diâmetro de alívio é Dal = {} mm'.format(results['Dal']))
    st.write('O chanfro inferior do diâmetro de alívio é hDal = {} mm'.format(results['chanfro']))
    st.write('A altura do chanfro de alívio é de ch = {} mm'.format(results['chanfro']))
    st.write('O ângulo do chanfro superior é ach = {}°'.format(results['a_chanf']))
    st.write('A altura do chanfro superior é sch = {} mm'.format(results['hchanf']))
    st.write('A altura do diâmetro externo é hDmp = {} mm'.format(results['Hdex']))
    st.write('O diâmetro de acomodação do PTFE bipartido é DPTFE = {} mm'.format(results['dPTFE']))
    st.write('A profundidade de acomodação do PTFE é aPTFE = {} mm'.format(4))
    st.write('O canal da guia será Wgu = {} mm'.format(results['Wgu']))
    st.write('A profundidade do canal da guia a partir do topo do pistão é tWgu = {} mm'.format(8))
    st.write('O peso do pistão é {} kg'.format(results['peso_pistao']))
    st.write('')

    st.markdown('### 4 - Bipartido de PTFE')
    st.write('O diâmetro do PTFE bipartido é DPTFE = {} mm'.format(results['dPTFE']))
    st.write('A espessura do PTFE bipartido é tPTFE = {} mm'.format(8))
    st.write('O peso dos 2 PTFE bipartido é {} kg'.format(results['peso_ptfe']))
    st.write('')

    st.image('Imagem4.png')
    st.markdown('### 5 - Guia')
    st.write('A altura da guia é Tgu = {} mm'.format(results['Tgu']))
    st.write('A largura da guia é Wgu = {} mm'.format(results['Wgu']))
    st.write('O comprimento da guia é Lgu = {} mm'.format(results['Lgu']))
    st.write('O peso da guia é {} kg'.format(results['peso_guia']))
    st.write('')

    st.markdown('### 6 - CM Strip')
    st.write('A espessura do CM Strip é CM_t = {} mm'.format(results['CM_t']))
    st.write('A largura do CM Strip é Ws1 = {} mm'.format(results['Ws1']))
    st.write('O comprimento do CM Strip é Lgu = {} mm'.format(results['Lgu']))
    st.write('O peso dos 2 CM Strip é {} kg'.format(results['peso_Cmstrip']))
    st.write('')

    st.markdown('### 7 - Placa deslizante de inox')
    st.write('A espessura do inox é e_i = {} mm'.format(results['e_inox']))
    st.write('O comprimento do inox dobrado (perímetro externo) é L_i = {} mm'.format(results['L_inox']))
    st.write('O comprimento do inox é Lsp = {} mm'.format(results['Lsp']))
    st.write('O chanfro dos cantos do inox é ch_i = {} mm'.format(results['chanfro_inox']))
    st.write('O raio externo da dobra do inox é r_i = {} mm'.format(results['raio_inox']))
    st.write('O peso dos 2 inox é {} kg'.format(results['peso_inox']))
    st.write('')

    st.markdown('### 8 - Placa superior')
    st.write('A largura da placa superior é Wsp = {} mm'.format(results['Wsp']))
    st.write('O comprimento da placa superior é Lsp = {} mm'.format(results['Lsp']))
    st.write('A espessura da placa superior é Tsp = {} mm'.format(results['Tsp']))
    st.write('A largura do canal da placa superior é Wgu2 = {} mm'.format(results['Wgu2']))
    st.write('A profunidade do canal da placa superior é Csp = {} mm'.format(results['cavidade']))
    st.write('O peso da placa superior é {} kg'.format(results['peso_placa_sup']))
    st.write('')

