import streamlit as st
from .calculator import PotCalculator


def run_calculation(maxNsd: float, Vxd: float) -> None:
    """Execute the POT UNI calculation and display results via Streamlit."""
    results = PotCalculator(maxNsd, Vxd).calculate()

    st.markdown('### Dimensões gerais')
    st.write(f'A altura total do aparelho é {results.T_total} mm')
    st.write(f'O peso total do aparelho é {results.peso_total} kg')
    st.write('')
    st.image('Imagem3.png')

    st.markdown('### 1 - Elastômero')
    st.write(f'O Dp = {results.D} mm')
    st.write(f'A espessura é hr = {results.tmin} mm')
    st.write(f'O peso do elastômero é {results.peso_elastomero} kg')
    st.write('')

    st.image('Imagem5.png')
    st.markdown('### 2 - Pote')
    st.write(f'O diâmetro interno Dp = {results.D} mm')
    st.write(f'O diâmetro externo no pote é Dpot = {2 * results.B + results.D} mm')
    st.write(f'A espessura do anel do pote é tw = {results.B} mm')
    st.write(f'A profundidade do Dp é hp1 = {results.H} mm')
    st.write(f'O diâmetro do fundo do pote é Wpot = {results.D + results.B + results.B + results.solda + results.solda + 6} mm')
    st.write(f'A espessura do fundo do pote é tb = {results.T} mm')
    st.write(f'O cordão de solda é w = {results.solda} mm')
    st.write(f'O peso do pote é {results.peso_pote} kg')
    st.write('')

    st.markdown('### 3 - Pistão')
    st.write(f'O diâmetro de contato é Dp = {results.D} mm')
    st.write(f'A altura do diâmetro de contato é hw = {results.b} mm')
    st.write(f'O diâmetro externo do pistão é Dmp = {results.Dpiston} mm')
    st.write(f'A altura total do pistão é hp4 = {results.hpistao} mm')
    st.write(f'O diâmetro de alívio é Dal = {results.Dal} mm')
    st.write(f'O chanfro inferior do diâmetro de alívio é hDal = {results.chanfro} mm')
    st.write(f'A altura do chanfro de alívio é de ch = {results.chanfro} mm')
    st.write(f'O ângulo do chanfro superior é ach = {results.a_chanf}°')
    st.write(f'A altura do chanfro superior é sch = {results.hchanf} mm')
    st.write(f'A altura do diâmetro externo é hDmp = {results.Hdex} mm')
    st.write(f'O diâmetro de acomodação do PTFE bipartido é DPTFE = {results.dPTFE} mm')
    st.write('A profundidade de acomodação do PTFE é aPTFE = {} mm'.format(4))
    st.write(f'O canal da guia será Wgu = {results.Wgu} mm')
    st.write('A profundidade do canal da guia a partir do topo do pistão é tWgu = {} mm'.format(8))
    st.write(f'O peso do pistão é {results.peso_pistao} kg')
    st.write('')

    st.markdown('### 4 - Bipartido de PTFE')
    st.write(f'O diâmetro do PTFE bipartido é DPTFE = {results.dPTFE} mm')
    st.write('A espessura do PTFE bipartido é tPTFE = {} mm'.format(8))
    st.write(f'O peso dos 2 PTFE bipartido é {results.peso_ptfe} kg')
    st.write('')

    st.image('Imagem4.png')
    st.markdown('### 5 - Guia')
    st.write(f'A altura da guia é Tgu = {results.Tgu} mm')
    st.write(f'A largura da guia é Wgu = {results.Wgu} mm')
    st.write(f'O comprimento da guia é Lgu = {results.Lgu} mm')
    st.write(f'O peso da guia é {results.peso_guia} kg')
    st.write('')

    st.markdown('### 6 - CM Strip')
    st.write(f'A espessura do CM Strip é CM_t = {results.CM_t} mm')
    st.write(f'A largura do CM Strip é Ws1 = {results.Ws1} mm')
    st.write(f'O comprimento do CM Strip é Lgu = {results.Lgu} mm')
    st.write(f'O peso dos 2 CM Strip é {results.peso_Cmstrip} kg')
    st.write('')

    st.markdown('### 7 - Placa deslizante de inox')
    st.write(f'A espessura do inox é e_i = {results.e_inox} mm')
    st.write(f'O comprimento do inox dobrado (perímetro externo) é L_i = {results.L_inox} mm')
    st.write(f'O comprimento do inox é Lsp = {results.Lsp} mm')
    st.write(f'O chanfro dos cantos do inox é ch_i = {results.chanfro_inox} mm')
    st.write(f'O raio externo da dobra do inox é r_i = {results.raio_inox} mm')
    st.write(f'O peso dos 2 inox é {results.peso_inox} kg')
    st.write('')

    st.markdown('### 8 - Placa superior')
    st.write(f'A largura da placa superior é Wsp = {results.Wsp} mm')
    st.write(f'O comprimento da placa superior é Lsp = {results.Lsp} mm')
    st.write(f'A espessura da placa superior é Tsp = {results.Tsp} mm')
    st.write(f'A largura do canal da placa superior é Wgu2 = {results.Wgu2} mm')
    st.write(f'A profunidade do canal da placa superior é Csp = {results.cavidade} mm')
    st.write(f'O peso da placa superior é {results.peso_placa_sup} kg')
    st.write('')

